package com.example.notes.bdd;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.web.reactive.server.EntityExchangeResult;
import org.springframework.test.web.reactive.server.WebTestClient;

import com.example.notes.audit.AuditRecordRepository;
import com.example.notes.note.NoteRepository;
import com.example.notes.note.api.CreateNoteRequest;
import com.example.notes.note.api.NoteResponse;
import com.example.notes.note.api.UpdateNoteRequest;
import com.example.notes.security.DataClassification;

import io.cucumber.java.Before;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

/**
 * Step definitions backing the Gherkin scenarios under {@code src/test/resources/features}.
 * Every step talks to the real HTTP API and database through {@link WebTestClient}, the same
 * way {@code NoteApiIntegrationTest} does — this suite adds business-readable acceptance
 * scenarios on top, it does not replace the lower-level integration tests.
 */
public class NoteBehaviorSteps {
    @Autowired
    private WebTestClient client;

    @Autowired
    private NoteRepository noteRepository;

    @Autowired
    private AuditRecordRepository auditRepository;

    @Autowired
    private ScenarioState state;

    @Autowired
    private ObjectMapper objectMapper;

    @Before
    public void resetDatabase() {
        noteRepository.deleteAll().block();
        auditRepository.deleteAll().block();
    }

    // ---- Given: workspace setup -------------------------------------------------------

    @Given("a clean workspace for team {string}")
    public void aCleanWorkspaceForTeam(String team) {
        state.setTeam(team);
    }

    // ---- Given/When: creating notes ----------------------------------------------------

    @Given("operator {string} with clearance {string} creates a {string} note titled {string}")
    public void operatorCreatesNote(String userId, String clearance, String classification, String title) {
        createNote(userId, clearance, classification, title, state.team());
        assertThat(state.lastStatus())
                .as("expected note creation to succeed for the scenario setup")
                .isEqualTo(201);
    }

    @Given("operator {string} with clearance {string} creates a {string} note titled {string} for team {string}")
    public void operatorCreatesNoteForTeam(
            String userId, String clearance, String classification, String title, String team) {
        createNote(userId, clearance, classification, title, team);
        assertThat(state.lastStatus())
                .as("expected note creation to succeed for the scenario setup")
                .isEqualTo(201);
    }

    @When("operator {string} with clearance {string} attempts to create a {string} note titled {string}")
    public void operatorAttemptsToCreateNote(String userId, String clearance, String classification, String title) {
        createNote(userId, clearance, classification, title, state.team());
    }

    private void createNote(String userId, String clearance, String classification, String title, String team) {
        EntityExchangeResult<byte[]> result = client.post()
                .uri("/api/teams/{team}/notes", team)
                .headers(headers -> {
                    headers.set("X-User-Id", userId);
                    headers.set("X-User-Clearance", clearance);
                })
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(new CreateNoteRequest(
                        title, "Generated by a BDD scenario.", DataClassification.valueOf(classification)))
                .exchange()
                .expectBody(byte[].class)
                .returnResult();

        capture(result, title);
    }

    // ---- When: listing and fetching ----------------------------------------------------

    @When("operator {string} with clearance {string} lists notes for team {string}")
    public void operatorListsNotes(String userId, String clearance, String team) {
        WebTestClient.ResponseSpec response = client.get()
                .uri("/api/teams/{team}/notes", team)
                .headers(headers -> {
                    headers.set("X-User-Id", userId);
                    headers.set("X-User-Clearance", clearance);
                })
                .exchange();

        EntityExchangeResult<List<NoteResponse>> result = response
                .expectBody(new org.springframework.core.ParameterizedTypeReference<List<NoteResponse>>() {
                })
                .returnResult();

        state.setLastStatus(result.getStatus().value());
        state.setLastNoteList(result.getResponseBody());
    }

    @When("operator {string} with clearance {string} fetches that note directly")
    public void operatorFetchesThatNoteDirectly(String userId, String clearance) {
        Long id = state.lastReferencedCurrent().id();
        fetchNote(userId, clearance, state.team(), id, state.lastReferencedTitle());
    }

    @Then("fetching that note as {string} with clearance {string} should return {int}")
    public void fetchingThatNoteShouldReturn(String userId, String clearance, int expectedStatus) {
        Long id = state.lastReferencedCurrent().id();
        fetchNote(userId, clearance, state.team(), id, state.lastReferencedTitle());
        assertThat(state.lastStatus()).isEqualTo(expectedStatus);
    }

    private void fetchNote(String userId, String clearance, String team, Long id, String title) {
        EntityExchangeResult<byte[]> result = client.get()
                .uri("/api/teams/{team}/notes/{id}", team, id)
                .headers(headers -> {
                    headers.set("X-User-Id", userId);
                    headers.set("X-User-Clearance", clearance);
                })
                .exchange()
                .expectBody(byte[].class)
                .returnResult();

        capture(result, title);
    }

    // ---- Given/When: updating -----------------------------------------------------------

    @Given("operator {string} with clearance {string} updates that note's content to {string}")
    public void operatorUpdatesThatNoteContent(String userId, String clearance, String newContent) {
        NoteResponse current = state.lastReferencedCurrent();
        updateNote(userId, clearance, state.team(), current, newContent, current.version());
        assertThat(state.lastStatus()).as("expected the update to succeed").isEqualTo(200);
    }

    @When("operator {string} with clearance {string} attempts to update the original version of that note "
            + "with content {string}")
    public void operatorAttemptsToUpdateOriginalVersion(String userId, String clearance, String newContent) {
        NoteResponse original = state.lastReferencedOriginal();
        updateNote(userId, clearance, state.team(), original, newContent, original.version());
    }

    private void updateNote(
            String userId, String clearance, String team, NoteResponse note, String newContent, Long version) {
        EntityExchangeResult<byte[]> result = client.put()
                .uri("/api/teams/{team}/notes/{id}", team, note.id())
                .headers(headers -> {
                    headers.set("X-User-Id", userId);
                    headers.set("X-User-Clearance", clearance);
                })
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(new UpdateNoteRequest(note.title(), newContent, version))
                .exchange()
                .expectBody(byte[].class)
                .returnResult();

        capture(result, note.title());
    }

    // ---- When: archive / restore / delete ------------------------------------------------

    @When("operator {string} with clearance {string} archives that note")
    public void operatorArchivesThatNote(String userId, String clearance) {
        setArchived(userId, clearance, true);
    }

    @When("operator {string} with clearance {string} restores that note")
    public void operatorRestoresThatNote(String userId, String clearance) {
        setArchived(userId, clearance, false);
    }

    private void setArchived(String userId, String clearance, boolean archived) {
        NoteResponse current = state.lastReferencedCurrent();
        String title = state.lastReferencedTitle();

        EntityExchangeResult<byte[]> result = client.patch()
                .uri("/api/teams/{team}/notes/{id}/archive?archived={archived}", state.team(), current.id(), archived)
                .headers(headers -> {
                    headers.set("X-User-Id", userId);
                    headers.set("X-User-Clearance", clearance);
                })
                .exchange()
                .expectBody(byte[].class)
                .returnResult();

        capture(result, title);
        assertThat(state.lastStatus()).as("expected the archive/restore call to succeed").isEqualTo(200);
    }

    @When("operator {string} with clearance {string} deletes that note")
    public void operatorDeletesThatNote(String userId, String clearance) {
        NoteResponse current = state.lastReferencedCurrent();

        EntityExchangeResult<byte[]> result = client.delete()
                .uri("/api/teams/{team}/notes/{id}", state.team(), current.id())
                .headers(headers -> {
                    headers.set("X-User-Id", userId);
                    headers.set("X-User-Clearance", clearance);
                })
                .exchange()
                .expectBody(byte[].class)
                .returnResult();

        state.setLastStatus(result.getStatus().value());
    }

    // ---- Then: assertions ----------------------------------------------------------------

    @Then("the response status should be {int}")
    public void theResponseStatusShouldBe(int expectedStatus) {
        assertThat(state.lastStatus()).isEqualTo(expectedStatus);
    }

    @Then("the note list should contain {int} notes")
    public void theNoteListShouldContainNotes(int expectedSize) {
        assertThat(state.lastNoteList()).hasSize(expectedSize);
    }

    @Then("the error code should be {string}")
    public void theErrorCodeShouldBe(String expectedErrorCode) {
        assertThat(state.lastErrorCode()).isEqualTo(expectedErrorCode);
    }

    @Then("the note's status should be {string}")
    public void theNotesStatusShouldBe(String expectedStatus) {
        assertThat(state.lastReferencedCurrent().status().name()).isEqualTo(expectedStatus);
    }

    @Then("an audit record with action {string} should exist for that note")
    public void anAuditRecordWithActionShouldExistForThatNote(String action) {
        Long noteId = state.lastReferencedCurrent() != null
                ? state.lastReferencedCurrent().id()
                : state.lastReferencedOriginal().id();

        boolean found = auditRepository.findAllByTeamIdOrderByOccurredAtDesc(state.team())
                .collectList()
                .block()
                .stream()
                .anyMatch(record -> record.noteId().equals(noteId) && record.action().equals(action));

        assertThat(found)
                .as("expected an audit record with action '%s' for note %d", action, noteId)
                .isTrue();
    }

    // ---- Response capture helper -----------------------------------------------------------

    /**
     * Records the HTTP status for every action, and — depending on whether the response body
     * is a note or a Problem Details error — either remembers the note (keyed by title) or
     * captures the error code/title so later {@code Then} steps can assert on either outcome.
     */
    private void capture(EntityExchangeResult<byte[]> result, String title) {
        state.setLastStatus(result.getStatus().value());
        byte[] body = result.getResponseBody();
        if (body == null || body.length == 0) {
            return;
        }

        JsonNode json;
        try {
            json = objectMapper.readTree(body);
        } catch (Exception e) {
            return;
        }

        if (json.has("errorCode")) {
            state.setLastErrorCode(json.get("errorCode").asString());
            state.setLastErrorTitle(json.has("title") ? json.get("title").asString() : null);
            return;
        }

        if (json.has("id") && title != null) {
            try {
                NoteResponse note = objectMapper.treeToValue(json, NoteResponse.class);
                if (state.originalByTitle(title) == null) {
                    state.rememberCreated(title, note);
                } else {
                    state.rememberCurrent(title, note);
                }
            } catch (Exception ignored) {
                // Not a note body (e.g. an empty/void response) — nothing further to capture.
            }
        }
    }
}
