CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id VARCHAR(64) NOT NULL,
    author_id VARCHAR(64) NOT NULL,
    title VARCHAR(120) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    classification VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_notes_team_updated
    ON notes(team_id, updated_at);

CREATE INDEX IF NOT EXISTS idx_notes_team_status
    ON notes(team_id, status);

CREATE TABLE IF NOT EXISTS audit_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id VARCHAR(64) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    note_id BIGINT NOT NULL,
    classification VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_team_occurred
    ON audit_records(team_id, occurred_at);
